spring.application.name: "tracerapp"
server:
  port: 9090
#logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  endpoints.web.exposure.include: '*' # health,info,prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  tracing:
    enabled: true
    sampling.probability: 1.0